server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    gzip on;
<<<<<<< HEAD
    gzip_vary on;
    gzip_types text/plain text/css application/json application/javascript text/javascript;

    # Angular SPA routing
=======
    gzip_types text/plain text/css application/json application/javascript text/javascript;

>>>>>>> 4c8a8b9a6444978bb654de3ea87c66b44c357391
    location / {
        try_files $uri $uri/ /index.html;
    }

<<<<<<< HEAD
    # Cache static assets
=======
    location /graphql {
        proxy_pass http://backend:4000/graphql;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

>>>>>>> 4c8a8b9a6444978bb654de3ea87c66b44c357391
    location ~* \.(js|css|png|jpg|ico|svg|woff2?)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}
